### ISSUE TITLE
Could you please post the usage guide? Thank you!

### ISSUE THREAD

**Issue by samsdolphin** [icsl-Jeon/traj_gen_vis#2]

**Comment by samsdolphin** [comment]
I find a simulation procedure where you first roslaunch `simulation_without_gazebo.launch`, then `connect ROS` and load `path3.txt` as target waypoints. Generate target trajectory and press `simulation activate`.

**Comment by icsl-Jeon** [comment]
My apology.... I will post instructions as soon as possible !! Your approach is right. 

Hope you could check the updated instruction soon~~ 

Thank you. 

BS.
