### ISSUE TITLE
a question about paper

### ISSUE THREAD

**Issue by wqwanghanzhang** [icsl-Jeon/traj_gen_vis#5]
hi,thanks for your sharing!
After reading two papers in this repo, i am confused about the planning of yaw, how to plan the yaw to make "xc(τ) heads toward xp(τ) at each time step", there is little information about it. if i can find it in the code?

**Comment by icsl-Jeon** [comment]
at 268 line of traj_gen_vis/src/auto_chaser/Wrapper.cpp, you can find the below:

```
    float yaw = atan2(-chaser_pose.pose.position.y+target_pose.pose.position.y,
                        -chaser_pose.pose.position.x+target_pose.pose.position.x);
```

Not a difficult  stuff :) just decide it instantly in x-y plane. Thank you for having an interest in my papers!

**Comment by wqwanghanzhang** [comment]
thank you for your reply!
